"""Where the packaged Helm chart lives, and how a cluster reaches it.

The chart is packaged into the UI's static tree at build time (see
``hack/install.sh``), which the server already mounts at ``/static``. So it is
served without a route of its own, and the URL the in-cluster bootstrap Job
installs from is just the server's own address plus a fixed path.

Serving it from the server rather than baking it into an image is what keeps the
chart and the registration manifest in step: both come from the same process, so
a cluster can never be handed a manifest that references values a different
chart version would read. It also needs no egress — the cluster must already
reach the server to register at all.
"""

import pathlib

# Relative to ``gpustack/ui``, which ``gpustack/routes/ui.py`` mounts as
# ``/static``. Fixed rather than versioned: the manifest that references this is
# regenerated by the same server that serves it, so putting a version in the URL
# would be a second thing to keep in step for no gain.
CHART_STATIC_PATH = "static/charts/gpustack-chart.tgz"

_UI_DIR = pathlib.Path(__file__).resolve().parents[1] / "ui"


def chart_asset_path() -> pathlib.Path:
    """Filesystem path of the packaged chart inside this installation."""
    return _UI_DIR / CHART_STATIC_PATH


def chart_available() -> bool:
    """Whether this installation actually carries the packaged chart.

    A source checkout that has not run ``make deps`` does not, and neither does
    one built with ``CHART_PACKAGE=false``. Callers rendering a manifest that
    points at the chart check this first, so the failure names the missing build
    step instead of surfacing as a 404 inside the cluster minutes later.
    """
    return chart_asset_path().is_file()


def chart_download_url(server_url: str) -> str:
    """URL an in-cluster Job can install the chart from.

    ``server_url`` is the address the cluster already registers against, so
    whatever reachability and TLS story applies to registration applies here
    too, unchanged.
    """
    return f"{server_url.rstrip('/')}/{CHART_STATIC_PATH}"
